### PR TITLE
feat: finalize basic i18n support

### PR DESCRIPTION
**Pull request by Nemikolh**
This PR completes the initial i18n support added in #127 for the remaining part of the UI where text should be customizable.

### CODE REVIEW

**Review by AriPerkkio — APPROVED** [review]
Looks good to me!

In future we'll need to be careful with the `packages/components/react` package. Exported public components should not define any texts that need localizing. They should always accept them as props.

**Comment by Nemikolh** [comment]
> Exported public components should not define any texts that need localizing. They should always accept them as props.

That's a very good point. Maybe we should write that down in a `README.md` or `CONTRIBUTING.md`.

What do you think?

**Comment by AriPerkkio** [comment]
That would be great. I've been planning to create good `CONTRIBUTING.md` once #128 is done. 

For ESLint I've used this kind of rule before: https://gist.github.com/AriPerkkio/fab0f24753b0f8457b63da187a4aee9e. That restricts importing from specific directories from files that inside specific directories. E.g. prevent importing from `packages/admin` in files that are inside `packages/user`.

**Comment by Nemikolh** [comment]
Oh interesting! I like a lot the idea of using eslint to enforce this.

From a quick look around, this eslint rule came up: https://github.com/jsx-eslint/eslint-plugin-react/blob/master/docs/rules/jsx-no-literals.md

It's not perfect but it would caught a few usecase.

**Review by AriPerkkio — APPROVED** [review]

**Pull request merged**
