### PR TITLE
feat: add support for StackBlitz Enterprise

### PR DESCRIPTION
**Pull request by Nemikolh**
This PR makes it possible for developers that want to use TutorialKit with StackBlitz Enterprise to do so. It adds a new CLI flag `--enterprise` and asks an additional question to fullfill this usecase.

Enterprise support can be added post project creation by manually creating a `tutorialkit.config.json` that includes an `enterprise` field with the correct properties.

On StackBlitz Enterprise authentication is necessary, and the UI includes a `Login` button on the top right corner to give a way for users to sign in. This button is not visible when enterprise is not configured.

### CODE REVIEW

**Review by d3lm — CHANGES_REQUESTED** [review]
Wooo nice one Joan! Cool that SB Enterprise is integrated 🔥

**Review by d3lm — COMMENTED** [review]
Some additional minor comments.

**Review by d3lm — COMMENTED** [review]
I can have a closer look and help more tomorrow if still needed.

**Review by d3lm — APPROVED** [review]
This looks great. Thanks Joan for addressing all the feedback 🙏

**Review by donmckenna — APPROVED** [review]
Looks good to me too, thanks for addressing the issues @Nemikolh ❤️

**Pull request merged**
